### ISSUE TITLE
do not install

### ISSUE THREAD

**Issue by axwell** [rak8s/rak8s#22]
this caused kernel panic on all of my pi's. 
Do not install !

**Comment by asachs01** [comment]
@axwell do you have any errors, or logs that you can point to prior to the kernel panic? A number of folks have gone through the process (myself included), and haven't had a kernel panic. 

> Do not install !

 ^ Doesn't really give much context to your setup, what Pi's you have, or show that any sort of troubleshooting was done aside from potentially running project blindly. A better approach would be to show the folks using this project some logs, screenshots, and walk us through what you did so that we can attempt to replicate it and fix it. By telling the rest of us `Do not install !`, you've painted yourself into a corner, because no one can help you at this point without further context.

**Comment by chris-short** [comment]
@axwell This is not a helpful comment at all. Please provide helpful context before telling people not to install. This is not an issue, this is whining.

**Comment by mohankumargupta** [comment]
Not sure, but problem may be that you need to pass argument for inventory file, otherwise it will target localhost,

ie.

ansible -i inventory -m ping all
ansible-playbook -i inventory cluster.yml

Also, with SSH keyless authentication, adding ansible_user=pi to inventory file for each node.
